DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS post;
DROP TABLE IF EXISTS task;

CREATE TABLE task (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	deleted_flag INTEGER DEFAULT 0, 
	description VARCHAR(100) NOT NULL
);